Init api
juke-space/crate-digger-model pull request #1
Opened 2024-08-09 00:20 UTC by car-d00r

# Overview
Creates an initial data model for the crate digger API. Defines a single endpoint: artist. The generated server code is python and the generated client is typescript. 
# Testing
Follow the install and build instructions in the readme. Note anything wrong or unclear.

2024-08-21 23:41 UTC, car-d00r commented
TODO: Add a persistent requirements.txt file without the conflicting lines.

2024-08-29 22:57 UTC, rafarrel reviewed
TEST: Building [PASS]

2024-08-29 22:57 UTC, rafarrel commented on README.md
> +4. Run ```sdk install gradle 8.9```
I'm guessing steps 3 and 4 are the versions to install for step 2, and not separate installations that should happen on top of step 2? If so, I would remove step 2 as it's a bit confusing to have it there.

2024-08-30 00:22 UTC, rafarrel reviewed
TEST: Packing-python [FAIL] ---> directory doesn't exist (see review comment for README)

2024-08-30 00:22 UTC, rafarrel commented on README.md
> +4. Run ```sdk install gradle 8.9```
Would also switch it to look more like this --->

1) Install [sdk man](https://sdkman.io/install)
2) Run:
```
sdk install java 21.0.3-tem &&
sdk install gradle 8.9
```

---> This way it can be copy and pasted into the terminal and run in one go. Also looks sleek 😄

2024-08-30 00:22 UTC, rafarrel commented on README.md
> +```gradle build```
Would change to ---> 

Run:
```
gradle build
```

2024-08-30 00:22 UTC, rafarrel commented on README.md
> +5. ```pdm build```
Would change to --->

Run:
```
python -m venv .venv &&
source .venv/bin/activate &&
...
pdm build
```

2024-08-30 00:22 UTC, rafarrel commented on README.md
> +6. ```npm pack```
Same as above.

2024-08-30 00:22 UTC, rafarrel commented on README.md
> +3. ```cd crate-server/build/generated/python-client/```
Not seeing the 'python-client' directory when cd-ing into 'generated'. Mine looks like this:
![image](https://github.com/user-attachments/assets/03e74278-3dfb-4140-8fc9-5ec369366b5a)


Here's what it looks like inside that directory:
![image](https://github.com/user-attachments/assets/ef0dcd30-6779-48bb-a2d5-cf3ecf9b25fe)


Ran gradle build and everything. Can't cd into this directory, not sure if this is an error?

2024-08-30 00:45 UTC, rafarrel reviewed
TEST: Packing-typescript-client [PASS]

2024-08-30 00:45 UTC, rafarrel commented on README.md
> +1. Make sure node and npm are installed.
Add installation link for node/npm. Maybe also add the required minimum version to run this operation?

It failed when I ran it with node v12.0.8. Upgraded to v22.7.0 and it worked. Not sure what the minimum required version is...

2024-08-30 00:45 UTC, rafarrel commented on README.md
> +6. ```npm pack```
Also, maybe add a note after the packing instructions describing where the packed build is located/what it would be called? Could be useful as a reference if we are packing a new version locally for testing with other microservices.

2024-09-04 00:15 UTC, car-d00r commented on README.md
> +3. ```cd crate-server/build/generated/python-client/```
I just made a typo, it should read cd crate-server/build/generated/crate-server/, updating

2024-09-04 00:16 UTC, car-d00r commented on README.md
> +1. Make sure node and npm are installed.
Will do

2024-09-04 01:03 UTC, car-d00r commented
@rafarrel all review comments resolved, take a look and let me know what you think.

2024-09-05 02:36 UTC, rafarrel requested changes

2024-09-05 02:36 UTC, rafarrel commented on README.md
> +sdk install java 21.0.3-tem
Add && to the end of this line since it's a dependency for the command after it. The && makes sure the second command is only run if the first one succeeds. 

Would honestly recommend doing that for all the command instructions in the README, especially the packing ones. The python building one got really messed up for me; The venv creation and cd commands failed on one test, so it tried packing it in my regular environment and got all janked leading to some unpleasant git cleanup lol. Better to avoid that happening and cancel immediately if one of the commands fails imo.

2024-09-05 02:36 UTC, rafarrel commented on README.md
> +pdm add  <path to crate-digger-model>/crate-server/build/generated/crate_server/dist/crate_server-0.1.0-py3-none-any.whl
Having a lot of issues with this...

When running in the root directory:

![image](https://github.com/user-attachments/assets/c3a7629d-b999-48ac-84ab-50a33a352b8d)


When running in the crate_server/dist directory:

![image](https://github.com/user-attachments/assets/94a1cd54-8e19-49c0-b075-dbdd055ceeeb)

Any ideas about what's going on?

2024-09-05 02:36 UTC, rafarrel commented on README.md
> +pdm build
Recommend adding && to the end of each line (except the last) like above.

2024-09-05 02:36 UTC, rafarrel commented on README.md
> +npm pack
Recommend adding && at the end of each line (except the last one) like above.

2024-09-05 02:37 UTC, rafarrel reviewed
TEST: Packing-python [PASS]

2024-09-05 02:37 UTC, rafarrel reviewed
TEST: Installing client (typescript) [PASS]

2024-09-10 00:19 UTC, rafarrel reviewed
TEST: Install packed build [PASS]

2024-09-10 00:20 UTC, rafarrel commented
Good to merge when &&'s are added to the end of commands 👍

2024-09-10 01:50 UTC, merged